# vim: sw=2:noai
---
- name: Install Base Packages
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant

  vars_files:
    - env_vars/ssl.yml

  vars:

    project_name: example-project
    application_name: djangoproj
    git_repo: https://github.com/mooja/mooja-django-stack.git
    git_branch: master

    # application settings
    virtualenv_path: "/webapps/{{ application_name }}"
    project_path: "{{ virtualenv_path }}/{{ project_name }}"
    application_log_dir: "{{ virtualenv_path }}/logs"
    application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
    requirements_file: "{{ project_path }}/requirements.txt"

    # database settings
    db_user: "{{ application_name }}"
    db_name: "{{ application_name }}"
    db_password: password

    # nginx settings
    nginx_http_port: 80
    nginx_https_port: 443
    nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
    nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
    nginx_static_dir: "{{ virtualenv_path }}/static/"
    nginx_media_dir: "{{ virtualenv_path }}/media/"
    nginx_server_name: "{{ inventory_hostname }}"
    ssl_src_dir: ssl_self_signed
    ssl_dest_dir: /etc/ssl
    ssl_key_password: password
    
    # gunicorn settings
    gunicorn_user: "{{ application_name }}"
    gunicorn_group: webapps
    gunicorn_num_workers: 3
    gunicorn_max_requests: 0

    # django settings
    django_settings_file: "{{ application_name }}.settings.development"
    django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"
    run_django_db_migrations: yes
    run_django_collectstatic: yes

    # Django Environment variables
    django_environment:
      DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
      DJANGO_SECRET_KEY: "{{ django_secret_key }}"
      SECRET_KEY: "{{ django_secret_key }}"
      MEDIA_ROOT: "{{ nginx_media_dir }}"
      STATIC_ROOT: "{{ nginx_static_dir }}"
      DATABASE_USER: "{{ db_user }}"
      DATABASE_PASSWORD: "{{ db_password }}"
      DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@127.0.0.1/{{ application_name }}"
      EMAIL_HOST: "{{ email_host|default(omit) }}"
      EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
      EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
      BROKER_URL: "{{ broker_url|default(omit) }}"

    # apt settings
    update_apt_cache: yes

  roles:

    - base
    - db
    - app
